name: Build Local Launcher

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            goos: linux
            ext: ""
          - os: macos-latest
            goos: darwin
            ext: ""
          - os: windows-latest
            goos: windows
            ext: ".exe"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Build web (vite)
        run: |
          npm ci
          npm run build

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Prepare launcher dist
        run: |
          mkdir -p tools/local-launcher/dist
          rm -rf tools/local-launcher/dist/*
          cp -r dist/* tools/local-launcher/dist/

      - name: Build launcher
        working-directory: tools/local-launcher
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: amd64
        run: |
          out="balt-local${{ matrix.ext }}"
          go build -trimpath -ldflags="-s -w" -o "$out"
          echo "OUT=$out" >> $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: balt-local-${{ matrix.goos }}-amd64
          path: tools/local-launcher/${{ env.OUT }}

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts

      - uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}